BookCommerceCustom1/Controllers/KategoriaController.cs
using BookCommerceCustom1.Data;
using BookCommerceCustom1.Helpers;
using BookCommerceCustom1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookCommerceCustom1.Controllers
{
    [Authorize(Roles = Sd.RoliAdmin)]
    public class KategoriaController : Controller
    {
        private readonly Konteksti _konteksti;

        public KategoriaController(Konteksti konteksti 
            )
        {
            _konteksti = konteksti;
        }
        public IActionResult Listo()
        {
            var lista = _konteksti.Kategorite.ToList();
            return View(lista);
        }

        public IActionResult Krijo()
        {
            var entiteti = new Kategoria();
            return View(entiteti);
        }
        [HttpPost]
        public IActionResult Krijo(Kategoria entiteti)
        {
            if (ModelState.IsValid)
            {
                _konteksti.Kategorite.Add(entiteti);
                _konteksti.SaveChanges();
                TempData["suksesi"] = "U shtua me sukses";
                return RedirectToAction("Listo");
            }
            return View();
        }
        public IActionResult Ndrysho(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }

            var entiteti = _konteksti.Kategorite.FirstOrDefault(x => x.Id == id);
            if (entiteti==null)
            {
                return NotFound();
            }
            
            return View(entiteti);
        }
        [HttpPost]
        public IActionResult Ndrysho(Kategoria entiteti)
        {
            if (ModelState.IsValid)
            {
                _konteksti.Kategorite.Update(entiteti);
                _konteksti.SaveChanges();
                TempData["suksesi"] = "U ndryshua me sukses";
                return RedirectToAction("Listo");
            }
            return View();
        }
        public IActionResult Fshi(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var entiteti = _konteksti.Kategorite.FirstOrDefault(x => x.Id == id);
            if (entiteti == null)
            {
                return NotFound();
            }
            return View(entiteti);
        }
        [HttpPost,ActionName("Fshi")]
        public IActionResult FshiPost(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var entiteti = _konteksti.Kategorite.FirstOrDefault(x => x.Id == id);
            if (entiteti == null)
            {
                return NotFound();
            }

            _konteksti.Remove(entiteti);
            _konteksti.SaveChanges();
            TempData["suksesi"] = "U fshi me sukses";
            return RedirectToAction("Listo");
        }
    }
}

BookCommerceCustom1/Controllers/KompaniaController.cs
using BookCommerceCustom1.Data;
using BookCommerceCustom1.Helpers;
using BookCommerceCustom1.Models;
using BookCommerceCustom1.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookCommerceCustom1.Controllers
{
	[Authorize(Roles = Sd.RoliAdmin)]
	public class KompaniaController : Controller
    {
        private readonly Konteksti _konteksti;

        public KompaniaController(Konteksti konteksti)
        {
            _konteksti = konteksti;
        }
        public IActionResult Listo()
        {
            return View();
        }
        public IActionResult ShtoNdrysho(int? id)
        {
            Kompania kompania = new();

            if (id == null || id == 0)
            {
                return View(kompania);
            }
            else
            {
               var kompExistuese = _konteksti.Kompania.FirstOrDefault(u => u.Id == id);
                return View(kompExistuese);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ShtoNdrysho(Kompania obj)
        {

            if (ModelState.IsValid)
            {
                
                if (obj.Id == 0)
                {
                    _konteksti.Kompania.Add(obj);
                }
                else
                {
                    _konteksti.Kompania.Update(obj);
                }
                _konteksti.SaveChanges();
                TempData["suksesi"] = "Eshte shtuar me sukses";
                return RedirectToAction("Listo");
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult ListoTeGjitha()
        {
            var productList = _konteksti.Kompania.ToList();
            return Json(new { data = productList });
        }

        //POST
        [HttpDelete]
        public IActionResult Fshi(int id)
        {
            var obj = _konteksti.Kompania.FirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { statusi = false, mesazhi = "Nuk gjindet" });
            }

            
            _konteksti.Kompania.Remove(obj);
            _konteksti.SaveChanges();
            return Json(new { statusi = true, mesazhi = "U fshi me sukese" });

        }

    }
}

BookCommerceCustom1/Controllers/MbulesaController.cs
using BookCommerceCustom1.Data;
using BookCommerceCustom1.Helpers;
using BookCommerceCustom1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookCommerceCustom1.Controllers
{
	[Authorize(Roles = Sd.RoliAdmin)]
	public class MbulesaController : Controller
    {
        private readonly Konteksti _konteksti;

        public MbulesaController(Konteksti konteksti 
            )
        {
            _konteksti = konteksti;
        }
        public IActionResult Listo()
        {
            var lista = _konteksti.Mbulesa.ToList();
            return View(lista);
        }

        public IActionResult Krijo()
        {
            var entiteti = new Mbulesa();
            return View(entiteti);
        }
        [HttpPost]
        public IActionResult Krijo(Mbulesa entiteti)
        {
            if (ModelState.IsValid)
            {
                _konteksti.Mbulesa.Add(entiteti);
                _konteksti.SaveChanges();
                TempData["suksesi"] = "U shtua me sukses";
                return RedirectToAction("Listo");
            }
            return View();
        }
        public IActionResult Ndrysho(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }

            var entiteti = _konteksti.Mbulesa.FirstOrDefault(x => x.Id == id);
            if (entiteti==null)
            {
                return NotFound();
            }
            
            return View(entiteti);
        }
        [HttpPost]
        public IActionResult Ndrysho(Mbulesa entiteti)
        {
            if (ModelState.IsValid)
            {
                _konteksti.Mbulesa.Update(entiteti);
                _konteksti.SaveChanges();
                TempData["suksesi"] = "U ndryshua me sukses";
                return RedirectToAction("Listo");
            }
            return View();
        }
        public IActionResult Fshi(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var entiteti = _konteksti.Mbulesa.FirstOrDefault(x => x.Id == id);
            if (entiteti == null)
            {
                return NotFound();
            }
            return View(entiteti);
        }
        [HttpPost,ActionName("Fshi")]
        public IActionResult FshiPost(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var entiteti = _konteksti.Mbulesa.FirstOrDefault(x => x.Id == id);
            if (entiteti == null)
            {
                return NotFound();
            }

            _konteksti.Remove(entiteti);
            _konteksti.SaveChanges();
            TempData["suksesi"] = "U fshi me sukses";
            return RedirectToAction("Listo");
        }
    }
}

BookCommerceCustom1/Controllers/ProduktiController.cs
using BookCommerceCustom1.Data;
using BookCommerceCustom1.Helpers;
using BookCommerceCustom1.Models;
using BookCommerceCustom1.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookCommerceCustom1.Controllers
{
	[Authorize(Roles = Sd.RoliAdmin)]
	public class ProduktiController : Controller
    {
        private readonly Konteksti _konteksti;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProduktiController(Konteksti konteksti, IWebHostEnvironment hostEnvironment)
        {
            _konteksti = konteksti;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Listo()
        {
            return View();
        }
        public IActionResult ShtoNdrysho(int? id)
        {
            ProduktiViewModel productVM = new()
            {
                Produkti = new(),
                Kategorite = _konteksti.Kategorite.ToList().Select(i => new SelectListItem
                {
                    Text = i.Emri,
                    Value = i.Id.ToString()
                }),
                Mbulesat = _konteksti.Mbulesa.ToList().Select(i => new SelectListItem
                {
                    Text = i.Emri,
                    Value = i.Id.ToString()
                }),
            };

            if (id == null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                productVM.Produkti = _konteksti.Produktet.FirstOrDefault(u => u.Id == id);
                return View(productVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ShtoNdrysho(ProduktiViewModel obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"imazhet\produktet");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Produkti.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Produkti.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Produkti.ImageUrl = @"\imazhet\produktet\" + fileName + extension;

                }
                if (obj.Produkti.Id == 0)
                {
                    _konteksti.Produktet.Add(obj.Produkti);
                }
                else
                {
                    _konteksti.Produktet.Update(obj.Produkti);
                }
                _konteksti.SaveChanges();
                TempData["suksesi"] = "Eshte shtuar me sukses";
                return RedirectToAction("Listo");
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult ListoTeGjitha()
        {
            var productList = _konteksti.Produktet.Include(x => x.Kategoria).Include(x => x.Mbulesa).ToList();
            return Json(new { data = productList });
        }

        //POST
        [HttpDelete]
        public IActionResult Fshi(int id)
        {
            var obj = _konteksti.Produktet.FirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { statusi = false, mesazhi = "Nuk gjindet" });
            }

            var pathiIVjeter = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(pathiIVjeter))
            {
                System.IO.File.Delete(pathiIVjeter);
            }

            _konteksti.Produktet.Remove(obj);
            _konteksti.SaveChanges();
            return Json(new { statusi = true, mesazhi = "U fshi me sukese" });

        }

    }
}

BookCommerceCustom1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BookCommerceCustom1.Helpers
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookCommerceCustom1</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookCommerceCustom1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookCommerceCustom1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
	                <ul class="navbar-nav flex-grow-1">
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Kryesore</a>
		                </li>
		                @* <li class="nav-item"> *@
			               @*  <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
		                @* </li> *@
		                @if (User.IsInRole(Sd.RoliAdmin))
		                {
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Kategoria" asp-action="Listo">Kategorite</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Mbulesa" asp-action="Listo">Mbulesat</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Produkti" asp-action="Listo">Produktet</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Kompania" asp-action="Listo">Kompania</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Krijo perdorus</a>
			                </li>
		                }
                        
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="Shporta" asp-action="Listo">
				                @await Component.InvokeAsync("Shporta")
			                </a>
		                </li>

		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="Porosia" asp-action="Listo"> Porositë</a>
		                </li>
	                </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
<div class="container">
    <partial name="_Notification"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookCommerceCustom1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookCommerceCustom1/Views/Shared/_Notification.cshtml
@if(TempData["suksesi"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["suksesi"]');
	</script>
}
@if(TempData["gabimi"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["gabimi"]');
	</script>
}